### ISSUE TITLE
Error: No network specified. Cannot determine current network.

### ISSUE THREAD

**Issue by hswick** [Shrugs/proof-of-steak#2]
For some reason it is having trouble connecting to testrpc when I run truffle commands in the token directory.

**Comment by Shrugs** [comment]
ah, I'm using ganache by default. use `truffle test --network testrpc` to point it at testrpc

**Comment by hswick** [comment]
`Could not find suitable configuration file.`

**Comment by Shrugs** [comment]
Looks like it can't find `truffle.js`... any reason it wouldn't be able to find it? Are you on windows?

**Comment by hswick** [comment]
My bad, I don't think I was in the token directory. 

```
[token]: truffle test --network testrpc
Using network 'testrpc'.

Error: Error: Exceeds block gas limit
```

**Comment by Shrugs** [comment]
Whoops, needs to be updated to the mainnet block limit. use `npm run testrpc` to add that.

**Comment by hswick** [comment]
Sweet! Got it to work. You're a g.
